# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20170930_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='topcoder_handle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='codeforces',
            name='maximum_rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='codeforces',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='codeforces_handle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
