# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_topcoder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeforces',
            old_name='maximum_rating',
            new_name='max_rating',
        ),
        migrations.RenameField(
            model_name='topcoder',
            old_name='maximum_rating',
            new_name='max_rating',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='codeforces_handle',
            new_name='codeforces',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='topcoder_handle',
            new_name='topcoder',
        ),
    ]
